# Generated by Django 3.2.25 on 2024-04-26 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=25, verbose_name='Номер телефона')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Наименование объекта')),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='Расположение')),
                ('square', models.IntegerField(blank=True, null=True, verbose_name='Площадь')),
                ('style', models.CharField(blank=True, max_length=50, null=True, verbose_name='Стиль')),
                ('year', models.CharField(blank=True, max_length=50, null=True, verbose_name='Год')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотогорафия')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать запись')),
                ('is_published_index', models.BooleanField(default=False, verbose_name='Запись опубликована на главной')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
                'ordering': ['order', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Является опубликованым')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.portfolio', verbose_name='Портфолио')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['order'],
            },
        ),
    ]
